groups:
  - name: PrometheusTargetMissing
    rules:
      - alert: InstanceDown 
        expr: up == 0 
        for: 1m
        labels:
          severity: hight
        annotations:
          summary: PrometheusTargetMissing Instance Down (instance {{ $labels.instance }})
          description: "PrometheusTargetMissing took more than 1m to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          
      - alert: InstanceRestart
        expr: node_boot_time_seconds == 0
        for: 1m
        labels:
          severity: hight
        annotations:
          summary: PrometheusTargetRestart Instance restart (instance {{ $labels.instance }})
          description: "PrometheusTargetMissing took more than 1m to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSlowProbe
        expr: avg_over_time(probe_duration_seconds[1m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox slow probe (instance {{ $labels.instance }})
          description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          
      - alert: HttpStatusCode
        expr: probe_http_status_code <= 199 or probe_http_status_code >= 400
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
          description: "HTTP status code is not 200-300\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          
      - alert: SslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate will expire soon (instance {{ $labels.instance }})"
          description: "SSL certificate expires in 30 days\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: SslCertificateHasExpired
        expr: probe_ssl_earliest_cert_expiry - time()  <= 0
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "SSL certificate has expired (instance {{ $labels.instance }})"
          description: "SSL certificate has expired already\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
 
      - alert: HttpSlowRequests
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "HTTP slow requests (instance {{ $labels.instance }})"
          description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          
      - alert: SlowPing
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow ping (instance {{ $labels.instance }})"
          description: "Blackbox ping took more than 1s\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

