apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  DB_HOST: ZGI=
  DEBUG: "avEU6Q=="
  POSTGRES_DB: bhdFJLCsetnPWC25
  POSTGRES_PASSWORD: Mm6jVE9TmBSY=
  POSTGRES_USER: 2FcCqn==
  SECRET_KEY: hC8vXSgVerrGxa8X5AHXycwBrM9K2V6xBC7UMwjSnj==
